### ISSUE TITLE
Failed ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Olney1** [Henry1970/solana_send#1]
Hi, thanks for sharing this I have exactly the same issue that you did, can you let me know how you resolved this using the [Serpent Academy](https://www.youtube.com/channel/UCCYsMZ-ZE0BLlhzeroya7hg) code?

**Comment by Henry1970** [comment]
Yes, instead of importing the solana module in javascript (import * as solanaWeb3 from '@solana/web3.js';) I have put it in the html code but an older version ( <script src="https://unpkg .com/@solana/web3.js@v1.33.0/lib/index.iife.js"></script>) It is seen that the latest version has some problem or incompatibility. Cheers

**Comment by Olney1** [comment]
Thank you so much, I was pulling my hair out on this! Working now!
